language: node_js
node_js:
  - "10.15.1"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: "65.0"
services:
  - postgresql
install:
  - cd $TRAVIS_BUILD_DIR/frontend
  - yarn
  - cd $TRAVIS_BUILD_DIR/api
  - yarn
  - cd $TRAVIS_BUILD_DIR/hub/src/test/support/fake.cso
  - yarn
  - cd $TRAVIS_BUILD_DIR
  - yarn
before_script:
  - cd $TRAVIS_BUILD_DIR/hub/src/test/support/fake.cso
  - npm run start &
  - cd $TRAVIS_BUILD_DIR/hub
  - export COA_USER=ignored-by-fake-cso
  - export COA_PASSWORD=ignored-by-fake-cso
  - export COA_SEARCH_ENDPOINT=http4://localhost:5005/search
  - export COA_NAMESPACE=ignored-by-fake-cso
  - export COA_SEARCH_SOAP_ACTION=ignored-by-fake-cso
  - export COA_VIEW_CASE_BASICS_SOAP_ACTION=second-call
  - export COA_VIEW_CASE_PARTY_SOAP_ACTION=third-call
  - mvn test-compile exec:java -Pagainst-fake-cso &
  - cd $TRAVIS_BUILD_DIR/api
  - export HUB_URL=http://localhost:8888
  - export PGHOST=localhost
  - export PGDATABASE=ci
  - export PGUSER=postgres
  - export PGPASSWORD=
  - createdb $PGDATABASE
  - export OPENSHIFT_NODEJS_PORT=8081
  - node start.with.fake.credentials.js &
  - cd $TRAVIS_BUILD_DIR/frontend
  - node tests/support/fake.site.minder.js &
  - export NODE_ENV=development
  - export REACT_APP_API_URL=http://localhost:3333/court-of-appeal
  - export BROWSER=none
  - npm run start &
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/support/webdriver/linux
  - sleep 60
script:
  - npm run test
